# Generated by Django 5.2.6 on 2025-10-16 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(30, 'la description doit contenir au moins 3 caractere')]),
        ),
    ]
